name: Docker Image

on:
  push:
    paths-ignore:
      - ".gitlab-ci.yml"
    pull_request:

jobs:

  dist:
    name: Build Distributions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./docker.sh release
      - run: tar zcvf resources-public.tar.gz ./resources/public
      - uses: actions/upload-artifact@v2-preview
        with:
          path: resources-public.tar.gz
      - uses: actions/upload-artifact@v2-preview
        with:
          path: dist/*.zip
      - uses: actions/upload-artifact@v2-preview
        with:
          path: resources-public.tar.gz
      - uses: actions/upload-artifact@v2-preview
        with:
          path: dist/*.deb
      - uses: actions/upload-artifact@v2-preview
        with:
          path: dist/*.rpm

  windows:
    name: Building Windows Distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./docker.sh release-windows
      - uses: actions/upload-artifact@v2-preview
        with:
          path: dist/*.zip

  macos:
    name: Building MacOS Distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./docker.sh release-macos
      - uses: actions/upload-artifact@v2-preview
        with:
          path: dist/*.zip

  build:
    name: Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build --tag jasonish/evebox:master .
      - name: Push Docker image to hub.docker.com (only for master)
        if: github.ref == 'refs/heads/master'
        run: |
          echo ${{secrets.DOCKER_HUB_TOKEN}} | \
              docker login -u ${{secrets.DOCKER_HUB_USERNAME}} --password-stdin
          docker push jasonish/evebox:master
